export interface NewsItem {
  id: string
  title: string
  excerpt: string
  imageUrl: string
  date: string
}

export const newsItems: NewsItem[] = [
  {
    id: 'summer-hair-refresh',
    title: '夏のヘアリフレッシュキャンペーン開催中！今だけ特別価格でトリートメントサービスをご提供いたします',
    excerpt: '今夏は、すべてのカラーサービスが20%オフ。今すぐご予約して、輝きを放って！',
    imageUrl: '/images/news-image-01.png',
    date: '2024.07.15',
  },
  {
    id: 'keratin-treatment',
    title: 'ケラチントリートメント',
    excerpt:
      'サラサラでフリズのない髪を、サロンの新しいケラチントリートメントで実現します。今すぐご予約を！',
    imageUrl: '/images/news-image-02.png',
    date: '2024.06.28',
  },
  {
    id: 'seasonal-hair-trends',
    title: '今季注目のヘアトレンドスタイルを詳しくご紹介します',
    excerpt: '今シーズンの最新ヘアトレンドやスタイルをご紹介します。',
    imageUrl: '/images/news-image-03.png',
    date: '2024.06.10',
  },
  {
    id: 'hair-care-tips',
    title: 'プロが教えるヘアケアの基本テクニック',
    excerpt: '髪の健康とツヤを保つための、プロによるアドバイスをご紹介します。',
    imageUrl: '/images/news-image-04.png',
    date: '2024.05.22',
  },
  {
    id: 'special-offer',
    title: '期間限定特別オファーのお知らせ',
    excerpt: '当サロンのサービスや商品に関する限定割引や特典をご利用いただけます。',
    imageUrl: '/images/news-image-05.png',
    date: '2024.05.08',
  },
  {
    id: 'professional-hair-treatment',
    title: 'プロフェッショナルヘアトリートメントの効果と特徴',
    excerpt:
      'プロによるヘアトリートメントの効果や、髪の健康をどのように高めてくれるのかをご紹介します。',
    imageUrl: '/images/news-image-06.png',
    date: '2024.04.15',
  },
  // 追加の記事データ（テスト用）
  {
    id: 'winter-hair-care',
    title: '乾燥する冬の季節におすすめのヘアケア特集',
    excerpt: '乾燥する冬の季節に適したヘアケア方法をご紹介します。',
    imageUrl: '/images/news-image-01.png',
    date: '2024.12.05',
  },
  {
    id: 'new-year-special',
    title: '新年企画',
    excerpt: '新年を迎えるにあたって、新しいヘアスタイルで気分一新しませんか？',
    imageUrl: '/images/news-image-02.png',
    date: '2024.01.01',
  },
  {
    id: 'spring-collection',
    title: '春らしいカラーとスタイルの新コレクション',
    excerpt: '春らしい明るいカラーとスタイルで、新しい季節を迎えましょう。',
    imageUrl: '/images/news-image-03.png',
    date: '2024.03.20',
  },
  {
    id: 'summer-special',
    title: '夏を快適に過ごす限定サービス',
    excerpt: '暑い夏を快適に過ごすためのヘアスタイルとケアをご提案します。',
    imageUrl: '/images/news-image-04.png',
    date: '2024.07.01',
  },
  {
    id: 'autumn-trends',
    title: '秋のおすすめトレンドスタイル',
    excerpt: '秋らしい落ち着いたカラーとスタイルで、上品な印象を演出します。',
    imageUrl: '/images/news-image-05.png',
    date: '2024.09.15',
  },
  {
    id: 'christmas-special',
    title: 'クリスマスパーティーにぴったりの特別企画',
    excerpt: 'クリスマスパーティーにぴったりの華やかなヘアスタイルをご提案します。',
    imageUrl: '/images/news-image-06.png',
    date: '2024.12.20',
  },
  {
    id: 'new-year-new-look',
    title: '新年の新しいイメージチェンジスタイル',
    excerpt: '新しい年の始まりに、イメージチェンジで気分を一新しませんか。',
    imageUrl: '/images/news-image-01.png',
    date: '2024.01.05',
  },
  {
    id: 'valentines-day-style',
    title: 'バレンタインデーにおすすめのロマンティックスタイル',
    excerpt: '特別な日のための、ロマンティックなヘアアレンジをご提案します。',
    imageUrl: '/images/news-image-02.png',
    date: '2024.02.10',
  },
  {
    id: 'white-day-gift',
    title: 'ホワイトデーのお返しギフト特集',
    excerpt: '大切な人への贈り物に、ヘアケア製品はいかがですか。',
    imageUrl: '/images/news-image-03.png',
    date: '2024.03.05',
  },
  {
    id: 'graduation-ceremony-hair',
    title: '卒業式にふさわしい特別なヘアセット',
    excerpt: '晴れの日にふさわしい、思い出に残るヘアセットを。',
    imageUrl: '/images/news-image-04.png',
    date: '2024.03.15',
  },
  {
    id: 'entrance-ceremony-style',
    title: '入学式準備',
    excerpt: '新しい生活のスタートに、フレッシュなヘアスタイルを。',
    imageUrl: '/images/news-image-05.png',
    date: '2024.04.05',
  },
  {
    id: 'golden-week-offer',
    title: 'ゴールデンウィーク限定のお得な企画',
    excerpt: '連休中にリフレッシュ。お得なキャンペーンを実施中です。',
    imageUrl: '/images/news-image-06.png',
    date: '2024.04.25',
  },
  {
    id: 'mothers-day-present',
    title: '母の日ギフト',
    excerpt: '日頃の感謝を込めて、ヘッドスパのプレゼントはいかがですか。',
    imageUrl: '/images/news-image-01.png',
    date: '2024.05.10',
  },
  {
    id: 'rainy-season-hair-care',
    title: '梅雨の湿気に負けないヘアケア方法',
    excerpt: '湿気に負けない、まとまりやすい髪質へ改善します。',
    imageUrl: '/images/news-image-02.png',
    date: '2024.06.05',
  },
  {
    id: 'fathers-day-special',
    title: '父の日メンズヘアキャンペーン',
    excerpt: 'お父さんもカッコよく。メンズカットがお得になります。',
    imageUrl: '/images/news-image-03.png',
    date: '2024.06.15',
  },
  {
    id: 'early-summer-refresh',
    title: '初夏の紫外線対策ヘアリフレッシュ',
    excerpt: '紫外線対策もできる、夏向けトリートメントがおすすめです。',
    imageUrl: '/images/news-image-04.png',
    date: '2024.06.20',
  },
  {
    id: 'tanabata-event',
    title: '七夕特別イベントのご案内',
    excerpt: '短冊に願いを込めて。ささやかなプレゼントをご用意しています。',
    imageUrl: '/images/news-image-05.png',
    date: '2024.07.07',
  },
  {
    id: 'obon-holiday-notice',
    title: 'お盆休業のお知らせとご予約について',
    excerpt: '8月のお休みについてのご案内です。ご予約はお早めに。',
    imageUrl: '/images/news-image-06.png',
    date: '2024.08.10',
  },
  {
    id: 'autumn-color-campaign',
    title: '大人っぽい秋色カラーキャンペーン',
    excerpt: '深みのある秋色カラーで、大人っぽい雰囲気に。',
    imageUrl: '/images/news-image-01.png',
    date: '2024.09.20',
  },
  {
    id: 'respect-for-the-aged-day',
    title: '敬老の日ギフト',
    excerpt: 'おじいちゃん、おばあちゃんへのプレゼントに。',
    imageUrl: '/images/news-image-02.png',
    date: '2024.09.16',
  },
  {
    id: 'halloween-hair-arrange',
    title: 'ハロウィンパーティー向け特別ヘアアレンジ',
    excerpt: 'イベントがもっと楽しくなる、特別なヘアアレンジ。',
    imageUrl: '/images/news-image-03.png',
    date: '2024.10.25',
  },
  {
    id: 'culture-day-special',
    title: '文化の日特別企画',
    excerpt: '芸術の秋。いつもと違う自分を表現してみませんか。',
    imageUrl: '/images/news-image-04.png',
    date: '2024.11.03',
  },
  {
    id: 'end-of-year-hair-care',
    title: '年末年始に向けたヘアメンテナンス',
    excerpt: '今年一年頑張った髪にご褒美を。年内に髪を綺麗に。',
    imageUrl: '/images/news-image-05.png',
    date: '2024.12.15',
  },
]
